theme: minima
title: Nicole's Blog
author: Nicole
email: spangelocodes@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  I love learning, coding, languages, games and I'm an avid reader of fiction.
  "They who dream by day are cognizant of many things which escape those who dream only by night." E.A. Poe
# social links
twitter_username: PhoenyzFyre # DO NOT include the @ character, or else the build will fail!
github_username:  Spangelo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
